import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import { Badge, Button, Icon, SegmentedControl } from '@biweb/ui';
import { LineChart, Spark, exportCsv, nf } from './demo/charts';
import type { Marker } from './demo/charts';
import { COHORTS, DEVICES, FUNNEL, MEASURES, PATHS, REGIONS, SEGMENTS, SERVICES, TODAY, WINDOW_DAYS, analyse, anomalies, burnWindows, clockAt, dailyBurn, funnelCounts, retention, slaState } from './demo/data';
import type { Measure, Region, Segment, Service } from './demo/data';
import './demo-reports.css';

type DemoId = 'demo_anomaly' | 'demo_sla' | 'demo_customer';
const META: Record<DemoId, { title: string; sub: string; accent: string; icon: 'timeline' | 'kpi' | 'chart'; kicker: string }> = {
  demo_anomaly: { title: 'Anomaly Explorer', sub: 'Detecção de desvios em séries operacionais: baseline móvel, z-score e leitura assistida.', accent: '#e8734a', icon: 'timeline', kicker: 'Detecção' },
  demo_sla: { title: 'SLA & Risk Monitor', sub: 'Orçamento de erro, taxa de consumo, projeção de esgotamento e risco por serviço.', accent: '#4a8fe8', icon: 'kpi', kicker: 'Confiabilidade' },
  demo_customer: { title: 'Customer Behavior', sub: 'Onboarding, retenção por coorte e caminhos de ativação das contas.', accent: '#2fb8a0', icon: 'chart', kicker: 'Experiência' },
};

function Metric({ label, value, note, tone, spark, color }: { label: string; value: string; note: string; tone?: 'warning' | 'danger' | 'success'; spark?: number[]; color?: string }) {
  return <section className="demo-metric"><span>{label}</span><b className={tone ? `tone-${tone}` : ''}>{value}</b><small>{note}</small>{spark && <Spark values={spark} color={color ?? 'var(--demo-accent)'} />}</section>;
}
function Widget({ title, subtitle, children, className = '', actions }: { title: string; subtitle?: string; children: ReactNode; className?: string; actions?: ReactNode }) {
  return <section className={`bw-widget demo-widget ${className}`}><header><div><b>{title}</b>{subtitle && <small>{subtitle}</small>}</div>{actions}</header>{children}</section>;
}
const legend = (items: { color: string; label: string; dash?: boolean }[]) => <div className="demo-chart-legend">{items.map((i) => <span key={i.label}><i className={i.dash ? 'is-dash' : ''} style={{ background: i.dash ? 'none' : i.color, borderColor: i.color }} />{i.label}</span>)}</div>;

/* ───────────── Anomaly Explorer ───────────── */
function AnomalyReport({ refresh, stamp }: { refresh: number; stamp: (rows: (string | number)[][] | null) => void }) {
  const [region, setRegion] = useState<Region>('Oeste'), [measure, setMeasure] = useState<Measure>('Latência'), [k, setK] = useState(3.2), [live, setLive] = useState(false), [tick, setTick] = useState(0), [sel, setSel] = useState<string | null>(null), [hypothesis, setHypothesis] = useState(false);
  useEffect(() => { if (!live) return; const t = setInterval(() => setTick((v) => v >= 150 ? 0 : v + 1), 1100); return () => clearInterval(t); }, [live]);
  const start = 40 + tick, m = MEASURES[measure], fmt = (v: number) => `${nf(v, m.digits)}${m.unit === '%' ? '%' : ` ${m.unit}`}`;
  const points = useMemo(() => analyse(region, measure, start, 96, k, refresh), [region, measure, start, k, refresh]);
  const found = useMemo(() => anomalies(points), [points]);
  const active = found.find((a) => a.id === sel) ?? found[0];
  const heat = useMemo(() => REGIONS.map((r) => { const pts = analyse(r, measure, start, 96, k, refresh); return { r, cells: Array.from({ length: 12 }, (_, b) => Math.max(0, ...pts.slice(b * 8, b * 8 + 8).map((p) => p.z))), open: anomalies(pts).length }; }), [measure, start, k, refresh]);
  useEffect(() => { stamp([['região', 'medida', 'inicio', 'fim', 'pico', 'z', 'score', 'nivel'], ...found.map((a) => [region, measure, clockAt(a.start), clockAt(a.end), a.peak.value.toFixed(3), a.peak.z.toFixed(2), a.score, a.level])]); return () => stamp(null); }, [found, region, measure, stamp]);
  const markers: Marker[] = found.map((a) => ({ id: a.id, x: a.peak.i, y: a.peak.value, color: a.level === 'Crítica' ? 'var(--danger)' : 'var(--warning)', selected: a.id === active?.id, label: `Anomalia ${a.level} às ${clockAt(a.peak.i)}` }));
  const regionsOpen = heat.filter((h) => h.open).length, worst = found[0];
  return <>
    <div className="demo-context"><label>Região<select value={region} onChange={(e) => { setRegion(e.target.value as Region); setSel(null); }}>{REGIONS.map((r) => <option key={r}>{r}</option>)}</select></label><label>Medida<select value={measure} onChange={(e) => { setMeasure(e.target.value as Measure); setSel(null); }}>{Object.keys(MEASURES).map((x) => <option key={x}>{x}</option>)}</select></label>
      <label className="dm-slider">Sensibilidade <b>{k.toFixed(1)}σ</b><input type="range" min="2" max="5" step=".1" value={k} aria-label="Limiar de z-score" onChange={(e) => setK(Number(e.target.value))} /></label><span className="flex-1" />
      <Button size="sm" icon={live ? 'close' : 'play'} onPress={() => setLive(!live)}>{live ? 'Parar leitura ao vivo' : 'Leitura ao vivo'}</Button>{live && <span className="dm-live"><i />AO VIVO · {clockAt(start + 95)}</span>}</div>
    <div className="demo-metrics"><Metric label="Anomalias na janela" value={String(found.length)} note={`limiar ${k.toFixed(1)}σ · ${region}`} tone={found.length ? 'warning' : 'success'} spark={heat.find((h) => h.r === region)!.cells} color="var(--warning)" /><Metric label="Maior desvio" value={worst ? `${worst.peak.z.toFixed(1)}σ` : '—'} note={worst ? `${fmt(worst.peak.value)} às ${clockAt(worst.peak.i)}` : 'sem desvios'} tone={worst && worst.score >= 78 ? 'danger' : undefined} /><Metric label="Regiões afetadas" value={`${regionsOpen} / ${REGIONS.length}`} note="com ao menos uma anomalia" /><Metric label="Última leitura" value={clockAt(start + 95)} note="janela de 5 min · 8 h" /></div>
    <div className="demo-grid">
      <Widget title={`Observado × baseline · ${measure}`} subtitle={`${region} · baseline robusto de 8 h (mediana e MAD), faixa ±${k.toFixed(1)}σ · clique numa anomalia`} className="demo-wide">
        <LineChart ariaLabel={`Série de ${measure} em ${region}`} series={[{ pts: points.map((p) => ({ x: p.i, y: p.value })), color: 'var(--demo-accent)', width: 2.2 }, { pts: points.map((p) => ({ x: p.i, y: p.mean })), color: 'var(--text-muted)', dash: '4 4', width: 1.4 }]} band={points.map((p) => ({ x: p.i, lo: p.mean - k * p.sigma, hi: p.mean + k * p.sigma }))} markers={markers} onMarker={setSel}
          xTicks={Array.from({ length: 9 }, (_, i) => start + i * 12)} xLabel={clockAt} yFormat={(y) => nf(y, m.digits)} tooltip={(x) => { const p = points.find((q) => q.i === x)!; return <><b>{clockAt(x)}</b><span>Observado {fmt(p.value)}</span><span>Baseline {fmt(p.mean)}</span><span className={p.flagged ? 'tone-danger' : ''}>{p.z.toFixed(1)}σ</span></>; }} />
        {legend([{ color: 'var(--demo-accent)', label: 'Observado' }, { color: 'var(--text-muted)', label: 'Baseline', dash: true }, { color: 'var(--viz-seq-2)', label: `Faixa ±${k.toFixed(1)}σ` }, { color: 'var(--danger)', label: 'Anomalia' }])}
      </Widget>
      <Widget title="Mapa de calor regional" subtitle="Maior z-score por intervalo de 40 min · clique para trocar de região">
        <div className="dm-heat" role="table" aria-label="Z-score por região e horário">{heat.map((h) => <div className={`dm-heat-row${h.r === region ? ' is-active' : ''}`} key={h.r} role="row"><button onClick={() => { setRegion(h.r); setSel(null); }}>{h.r}</button>{h.cells.map((z, i) => <i key={i} role="cell" title={`${h.r} · ${clockAt(start + i * 8)} · ${z.toFixed(1)}σ`} style={{ ['--heat' as string]: Math.min(1, z / 6) }} />)}<em>{h.open || '–'}</em></div>)}<div className="dm-heat-axis"><span />{[0, 3, 6, 9].map((i) => <small key={i} style={{ gridColumn: `${i + 2} / span 3` }}>{clockAt(start + i * 8)}</small>)}<span /></div></div>
      </Widget>
      <Widget title="Anomalias detectadas" subtitle="Pontuação combina magnitude (σ) e duração">
        <div className="demo-anomaly-list">{found.length ? found.map((a) => <button key={a.id} className={`demo-anomaly-row${a.id === active?.id ? ' is-active' : ''}`} onClick={() => setSel(a.id)}><span><b>{clockAt(a.start)}–{clockAt(a.end)}</b><small>{fmt(a.peak.value)} no pico · {a.duration} min · {a.peak.z.toFixed(1)}σ</small></span><strong>{a.score}</strong><Badge tone={a.level === 'Crítica' ? 'danger' : 'warning'}>{a.level}</Badge></button>) : <p className="demo-note">Nenhum desvio acima de {k.toFixed(1)}σ nesta janela. Reduza o limiar ou avance a leitura ao vivo.</p>}</div>
      </Widget>
      <Widget title="Leitura assistida" subtitle="Evidência observada separada de hipótese" className="demo-wide">
        {active ? <div className="demo-evidence"><div><Badge tone="success" icon="check">Evidência</Badge><p>Em {region}, {measure.toLowerCase()} atingiu {fmt(active.peak.value)} às {clockAt(active.peak.i)}, contra referência de {fmt(active.peak.mean)} ({active.peak.z.toFixed(1)}σ). O desvio durou {active.duration} minutos e foi detectado em {clockAt(active.start)}.</p></div>
          <div><Badge tone="accent" icon="copilot">Hipótese</Badge><p>{hypothesis ? (measure === 'Disponibilidade' ? 'A queda é compatível com perda de redundância em um trecho. Confirme com o estado dos enlaces e o histórico de alarmes do mesmo período.' : 'A concentração temporal em uma só região é compatível com degradação de enlace ou saturação de rota. Isto é uma associação, não uma causa confirmada; valide a telemetria do equipamento.') : 'Possível degradação de enlace ou saturação. Abra para ver limitações e próximos passos.'}<button className="demo-inline-link" onClick={() => setHypothesis((v) => !v)}>{hypothesis ? 'Recolher' : 'Detalhar hipótese'}</button></p></div></div> : <p className="demo-note">Selecione uma anomalia para ver a evidência.</p>}
      </Widget>
    </div>
  </>;
}

/* ───────────── SLA & Risk ───────────── */
function SlaReport({ refresh, stamp }: { refresh: number; stamp: (rows: (string | number)[][] | null) => void }) {
  const [sid, setSid] = useState('gateway'), [what, setWhat] = useState(1), [extra, setExtra] = useState<Record<string, number>>({}), [log, setLog] = useState<{ t: string; text: string }[]>([]);
  void refresh;
  const svc = SERVICES.find((s) => s.id === sid)!, states = SERVICES.map((s) => ({ s, st: slaState(s, extra[s.id] ?? 0) })), cur = states.find((x) => x.s.id === sid)!.st;
  const days = dailyBurn(svc, extra[sid] ?? 0), cum: number[] = []; days.reduce((a, b, i) => (cum[i] = a + b, a + b), 0);
  const actual = [{ x: 0, y: 100 }, ...cum.map((c, i) => ({ x: i + 1, y: Math.max(0, 100 - c * 100) }))], rate = cur.consumed / TODAY, perDay = 1 / WINDOW_DAYS;
  const proj = Array.from({ length: WINDOW_DAYS - TODAY + 1 }, (_, i) => ({ x: TODAY + i, y: Math.max(0, 100 - (cur.consumed + rate * i) * 100) })), whatIf = Array.from({ length: WINDOW_DAYS - TODAY + 1 }, (_, i) => ({ x: TODAY + i, y: Math.max(0, 100 - (cur.consumed + perDay * what * i) * 100) }));
  const whatExhaust = perDay * what > 0 ? TODAY + (1 - cur.consumed) / (perDay * what) : null, windows = burnWindows(svc, extra[sid] ?? 0);
  const firing = states.filter((x) => x.st.status === 'Crítico').length, worst = [...states].sort((a, b) => b.st.consumed - a.st.consumed)[0]!;
  useEffect(() => { stamp([['serviço', 'SLO', 'orçamento consumido %', 'burn rate', 'esgota no dia', 'estado'], ...states.map(({ s, st }) => [s.name, s.slo, (st.consumed * 100).toFixed(1), st.burn.toFixed(2), st.exhaustDay ? st.exhaustDay.toFixed(0) : '>30', st.status])]); return () => stamp(null); }, [sid, extra, stamp]); // eslint-disable-line react-hooks/exhaustive-deps
  const simulate = () => { setExtra((e) => ({ ...e, [sid]: (e[sid] ?? 0) + 6 })); setLog((l) => [{ t: new Date().toLocaleTimeString('pt-BR'), text: `Incidente simulado em ${svc.name}: 30 min de erros elevados.` }, ...l].slice(0, 5)); };
  const tone = (s: string) => s === 'Crítico' ? 'danger' : s === 'Risco' ? 'warning' : 'success';
  const risk = (s: Service, st: ReturnType<typeof slaState>) => ({ p: Math.min(98, st.consumed * 70 + st.burn * 14), i: Math.min(96, s.customers / 1600 * ({ Crítico: 1.2, Alto: .9, Médio: .6 }[s.tier])) });
  return <>
    <div className="demo-context"><label>Serviço<select value={sid} onChange={(e) => setSid(e.target.value)}>{SERVICES.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="dm-slider">E se a taxa de consumo for <b>{nf(what, 1)}×</b><input type="range" min=".2" max="8" step=".1" value={what} aria-label="Taxa de consumo hipotética" onChange={(e) => setWhat(Number(e.target.value))} /></label><span className="flex-1" /><Button size="sm" icon="bolt" onPress={simulate}>Simular incidente</Button><Badge tone={firing ? 'danger' : 'success'} icon={firing ? 'warning' : 'check'}>{firing ? `${firing} em estado crítico` : 'Todos dentro do SLO'}</Badge></div>
    <div className="demo-metrics"><Metric label="Orçamento consumido" value={`${nf(cur.consumed * 100, 0)}%`} note={`${svc.name} · dia ${TODAY} de ${WINDOW_DAYS}`} tone={tone(cur.status)} spark={cum.map((c) => c * 100)} color="var(--demo-accent)" /><Metric label="Taxa de burn" value={`${nf(cur.burn, 1)}×`} note="1× é a taxa sustentável" tone={cur.burn > 2 ? 'danger' : cur.burn > 1.2 ? 'warning' : 'success'} /><Metric label="Esgota em" value={cur.exhaustDay ? `dia ${nf(cur.exhaustDay, 0)}` : 'após o ciclo'} note={cur.exhaustDay ? `${nf(Math.max(0, cur.exhaustDay - TODAY), 0)} dias no ritmo atual` : 'no ritmo atual'} tone={cur.exhaustDay && cur.exhaustDay < 26 ? 'danger' : undefined} /><Metric label="Maior consumo" value={worst.s.name.split(' ')[0]!} note={`${nf(worst.st.consumed * 100, 0)}% do orçamento`} tone={worst.st.consumed > .7 ? 'danger' : 'warning'} /></div>
    <div className="demo-grid">
      <Widget title={`Orçamento de erro restante · ${svc.name}`} subtitle={`SLO ${svc.slo}% em ${WINDOW_DAYS} dias · linha pontilhada = projeção`} className="demo-wide">
        <LineChart ariaLabel="Burndown do orçamento de erro" height={260} yDomain={[0, 100]} xTicks={[0, 5, 10, 15, 18, 20, 25, 30]} xLabel={(x) => `d${x}`} yFormat={(y) => `${nf(y, 0)}%`}
          series={[{ pts: actual, color: 'var(--demo-accent)', width: 2.6 }, { pts: [{ x: 0, y: 100 }, { x: WINDOW_DAYS, y: 0 }], color: 'var(--text-muted)', dash: '2 5', width: 1.2 }, { pts: proj, color: 'var(--danger)', dash: '6 4', width: 1.8 }, { pts: whatIf, color: 'var(--success)', dash: '2 3', width: 2 }]}
          vlines={[{ x: TODAY, label: 'hoje', color: 'var(--text-muted)' }, ...(cur.exhaustDay && cur.exhaustDay <= WINDOW_DAYS ? [{ x: cur.exhaustDay, label: 'esgota', color: 'var(--danger)' }] : [])]}
          tooltip={(x) => <><b>Dia {x}</b>{x <= TODAY ? <span>Restante {nf(actual[x]!.y, 1)}%</span> : <><span>Projeção {nf(proj[x - TODAY]!.y, 1)}%</span><span>Hipótese {nf(whatIf[x - TODAY]!.y, 1)}%</span></>}</>} />
        {legend([{ color: 'var(--demo-accent)', label: 'Restante' }, { color: 'var(--text-muted)', label: 'Consumo ideal', dash: true }, { color: 'var(--danger)', label: 'Projeção atual', dash: true }, { color: 'var(--success)', label: `Hipótese ${nf(what, 1)}×`, dash: true }])}
        <p className="demo-note">{cur.consumed >= 1 ? 'O orçamento deste ciclo já foi esgotado.' : whatExhaust && whatExhaust < WINDOW_DAYS ? `Com ${nf(what, 1)}× o orçamento esgota no dia ${nf(whatExhaust, 0)}.` : `Com ${nf(what, 1)}× o orçamento dura até o fim do ciclo.`} {cur.consumed < 1 && <>Reduzir de {nf(cur.burn, 1)}× para {nf(what, 1)}× {whatExhaust && cur.exhaustDay && whatExhaust > cur.exhaustDay ? `ganha ${nf(whatExhaust - cur.exhaustDay, 0)} dias.` : 'não altera a data.'}</>}</p>
      </Widget>
      <Widget title="Saúde e orçamento por serviço" subtitle="Clique numa linha para analisar" className="demo-wide"><div className="demo-table-wrap"><table className="bw-table demo-sla-table"><thead><tr><th>Serviço</th><th>Tier</th><th>SLO</th><th>Orçamento consumido</th><th>Burn</th><th>Tendência</th><th>Esgota</th><th>Estado</th></tr></thead><tbody>{states.map(({ s, st }) => <tr key={s.id} className={s.id === sid ? 'is-selected' : ''} onClick={() => setSid(s.id)} tabIndex={0} onKeyDown={(e) => { if (e.key === 'Enter') setSid(s.id); }}><td><b>{s.name}</b><small className="dm-sub">{s.owner}</small></td><td>{s.tier}</td><td>{s.slo}%</td><td><div className="demo-budget"><span><i style={{ width: `${Math.min(100, st.consumed * 100)}%`, background: `var(--${tone(st.status)})` }} /></span><b>{nf(st.consumed * 100, 0)}%</b></div></td><td>{nf(st.burn, 1)}×</td><td><Spark values={dailyBurn(s, extra[s.id] ?? 0).map((v, i, a) => a.slice(0, i + 1).reduce((x, y) => x + y, 0) * 100)} color={`var(--${tone(st.status)})`} /></td><td>{st.exhaustDay ? `dia ${nf(st.exhaustDay, 0)}` : '—'}</td><td><Badge tone={tone(st.status)}>{st.status}</Badge></td></tr>)}</tbody></table></div></Widget>
      <Widget title="Alertas por janela de consumo" subtitle="Política multi-janela: pagina quando consumo alto é sustentado"><div className="dm-windows">{windows.map((w) => { const on = w.value >= w.limit; return <div key={w.label} className={on ? 'is-on' : ''}><span><b>{w.label}</b><small>limite {nf(w.limit, 1)}×</small></span><i><u style={{ width: `${Math.min(100, w.value / (w.limit * 1.6) * 100)}%` }} /><s style={{ left: `${100 / 1.6}%` }} /></i><strong>{nf(w.value, 1)}×</strong><Badge tone={on ? 'danger' : w.value > w.limit * .6 ? 'warning' : 'success'}>{on ? (w.page ? 'Acionar' : 'Investigar') : w.value > w.limit * .6 ? 'Atenção' : 'OK'}</Badge></div>; })}</div>
        {log.length > 0 && <ul className="dm-log">{log.map((l, i) => <li key={i}><time>{l.t}</time>{l.text}</li>)}</ul>}</Widget>
      <Widget title="Matriz de risco" subtitle="Probabilidade de estourar o SLO × impacto nos clientes">
        <svg className="dm-risk" viewBox="0 0 320 220" role="img" aria-label="Matriz de risco dos serviços"><rect x="36" y="8" width="276" height="180" className="dm-risk-bg" /><rect x="174" y="8" width="138" height="90" className="dm-risk-hot" />{[0, 1].map((i) => <line key={i} x1={36 + 138 * (i + 1) * (i ? 0 : 1)} x2={36 + 138 * (i + 1) * (i ? 0 : 1)} y1="8" y2="188" className="dm-grid" />)}<line x1="36" x2="312" y1="98" y2="98" className="dm-grid" /><text x="174" y="206" textAnchor="middle">probabilidade →</text><text x="12" y="98" transform="rotate(-90 12 98)" textAnchor="middle">impacto →</text>
          {states.map(({ s, st }) => { const r = risk(s, st); return <g key={s.id} className="dm-bubble" role="button" tabIndex={0} aria-label={`${s.name}: ${st.status}`} onClick={() => setSid(s.id)} onKeyDown={(e) => { if (e.key === 'Enter') setSid(s.id); }}><circle cx={36 + r.p / 100 * 276} cy={188 - r.i / 100 * 180} r={s.id === sid ? 13 : 9} fill={`var(--${tone(st.status)})`} opacity={s.id === sid ? .95 : .6} stroke="var(--surface-panel)" strokeWidth="2" /><text x={36 + r.p / 100 * 276} y={188 - r.i / 100 * 180 - 15} textAnchor="middle">{s.name.split(' ')[0]}</text></g>; })}</svg>
      </Widget>
    </div>
  </>;
}

/* ───────────── Customer Behavior ───────────── */
function CustomerReport({ refresh, stamp }: { refresh: number; stamp: (rows: (string | number)[][] | null) => void }) {
  const [seg, setSeg] = useState<Segment>('Todos os clientes'), [compare, setCompare] = useState<Segment | 'Nenhum'>('Nenhum'), [step, setStep] = useState(2), [view, setView] = useState<'Jornada' | 'Coortes' | 'Caminhos'>('Jornada'), [hot, setHot] = useState<number | null>(null);
  const funnel = useMemo(() => funnelCounts(seg, refresh), [seg, refresh]), other = compare === 'Nenhum' ? null : funnelCounts(compare, refresh);
  const rate = (f: number[], i: number) => i ? f[i]! / f[i - 1]! : 1, drops = funnel.slice(1).map((n, i) => ({ i: i + 1, lost: funnel[i]! - n, pct: 1 - n / funnel[i]! })), worst = [...drops].sort((a, b) => b.pct - a.pct)[0]!;
  const act = funnel[4]! / funnel[0]!, bestSeg = SEGMENTS.slice(1).map((s) => ({ s, v: funnelCounts(s, refresh)[4]! / funnelCounts(s, refresh)[0]! })).sort((a, b) => b.v - a.v)[0]!;
  useEffect(() => { stamp([['etapa', 'contas', 'conversão da etapa %'], ...FUNNEL.map((f, i) => [f, funnel[i]!, (rate(funnel, i) * 100).toFixed(1)])]); return () => stamp(null); }, [funnel, stamp]); // eslint-disable-line react-hooks/exhaustive-deps
  const W = 640, H = 230, bw = 92, gap = (W - bw * 5) / 4, max = funnel[0]!, bh = (n: number) => n / max * (H - 70);
  const curves = COHORTS.map((c, ci) => ({ c, ci, pts: Array.from({ length: COHORTS.length - ci }, (_, m) => ({ x: m, y: retention(seg, ci, m)! })) }));
  const palette = ['#2fb8a0', '#4a8fe8', '#a78bfa', '#e8b84a', '#e8734a', '#d96a9a'];
  return <>
    <div className="demo-context"><label>Segmento<select value={seg} onChange={(e) => setSeg(e.target.value as Segment)}>{SEGMENTS.map((s) => <option key={s}>{s}</option>)}</select></label><label>Comparar com<select value={compare} onChange={(e) => setCompare(e.target.value as Segment | 'Nenhum')}><option>Nenhum</option>{SEGMENTS.filter((s) => s !== seg).map((s) => <option key={s}>{s}</option>)}</select></label><SegmentedControl label="Visão de comportamento" value={view} onChange={setView} options={[{ id: 'Jornada', label: 'Jornada' }, { id: 'Coortes', label: 'Coortes' }, { id: 'Caminhos', label: 'Caminhos' }]} /><span className="flex-1" /><Badge tone="neutral">Aquisição · últimos 6 meses</Badge></div>
    <div className="demo-metrics"><Metric label="Contas criadas" value={nf(funnel[0]!)} note={other ? `${compare}: ${nf(other[0]!)}` : 'no período'} /><Metric label="Ativação em 7 dias" value={`${nf(act * 100, 1)}%`} note={other ? `${compare}: ${nf(other[4]! / other[0]! * 100, 1)}%` : `${nf(funnel[4]!)} contas`} tone={act > .3 ? 'success' : 'warning'} spark={funnel.map((n) => n)} /><Metric label="Maior abandono" value={`${nf(worst.pct * 100, 0)}%`} note={`${FUNNEL[worst.i - 1]} → ${FUNNEL[worst.i]}`} tone="danger" /><Metric label="Melhor segmento" value={bestSeg.s} note={`${nf(bestSeg.v * 100, 1)}% de ativação`} tone="success" /></div>
    <div className="demo-grid">{view === 'Jornada' ? <>
      <Widget title="Funil de onboarding" subtitle="Clique numa etapa para ver o detalhe · a faixa vermelha mostra quem saiu" className="demo-wide">
        <svg className="dm-funnel" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Funil de onboarding">{funnel.map((n, i) => { const x = i * (bw + gap), h = bh(n), y = 30 + (H - 70 - h) / 2, nx = x + bw + gap, next = funnel[i + 1], nh = next ? bh(next) : 0, ny = 30 + (H - 70 - nh) / 2;
          return <g key={i}>{next !== undefined && <><path d={`M${x + bw},${y} C${x + bw + gap / 2},${y} ${nx - gap / 2},${ny} ${nx},${ny} L${nx},${ny + nh} C${nx - gap / 2},${ny + nh} ${x + bw + gap / 2},${y + h} ${x + bw},${y + h}Z`} className="dm-flow" /><path d={`M${x + bw},${y + h * (next / n)} C${x + bw + gap / 2},${y + h * (next / n)} ${nx - gap / 2},${ny + nh} ${nx},${ny + nh} L${nx},${ny + nh + 0.1} C${nx - gap / 2},${y + h} ${x + bw + gap / 2},${y + h} ${x + bw},${y + h}Z`} className="dm-drop" /></>}
            <g role="button" tabIndex={0} aria-label={`${FUNNEL[i]}: ${nf(n)} contas`} className={`dm-step${i === step ? ' is-active' : ''}`} onClick={() => setStep(i)} onKeyDown={(e) => { if (e.key === 'Enter') setStep(i); }}><rect x={x} y={y} width={bw} height={Math.max(4, h)} rx="4" />{other && <rect x={x} y={30 + (H - 70 - bh(other[i]! * funnel[0]! / other[0]!)) / 2} width="4" height={bh(other[i]! * funnel[0]! / other[0]!)} className="dm-cmp" />}<text x={x + bw / 2} y={y - 8} textAnchor="middle" className="dm-n">{nf(n)}</text><text x={x + bw / 2} y={H - 28} textAnchor="middle">{FUNNEL[i]}</text><text x={x + bw / 2} y={H - 14} textAnchor="middle" className="dm-pct">{i ? `${nf(rate(funnel, i) * 100, 1)}% da etapa anterior` : '100%'}</text></g></g>; })}</svg>
        {other && <p className="demo-note">A barra fina à esquerda de cada etapa é {compare}, normalizada para o mesmo tamanho inicial.</p>}
      </Widget>
      <Widget title={`Detalhe · ${FUNNEL[step]}`} subtitle="Distribuição por dispositivo e saída até a etapa seguinte"><div className="dm-bars">{Object.entries(DEVICES).map(([d, v]) => { const total = Object.values(DEVICES).reduce((a, b) => a + b[step]!, 0), share = v[step]! / total; return <div key={d}><span>{d}</span><i><u style={{ width: `${share * 100}%` }} /></i><b>{nf(funnel[step]! * share)}</b></div>; })}</div>{step < 4 && <p className="demo-note">{nf(drops[step]!.lost)} contas ({nf(drops[step]!.pct * 100, 0)}%) não avançam para “{FUNNEL[step + 1]}”.</p>}</Widget>
      <Widget title="Leituras automáticas" subtitle="Calculadas sobre o recorte atual"><ul className="dm-insights"><li><Icon name="warning" size={12} /><span>A maior perda está em <b>{FUNNEL[worst.i - 1]} → {FUNNEL[worst.i]}</b> ({nf(worst.pct * 100, 0)}%).</span></li><li><Icon name="check" size={12} /><span><b>{bestSeg.s}</b> ativa {nf((bestSeg.v - act) * 100, 1)} pp {bestSeg.v >= act ? 'acima' : 'abaixo'} do recorte.</span></li><li><Icon name="info" size={12} /><span>Associação observada entre conectar uma fonte na 1ª sessão e ativar; não indica causalidade.</span></li></ul></Widget></>
      : view === 'Coortes' ? <>
        <Widget title="Retenção por coorte" subtitle="Percentual das contas que retornaram em cada mês · passe o mouse para destacar" className="demo-wide"><div className="demo-cohort-wrap"><table className="demo-cohort"><thead><tr><th>Coorte</th>{COHORTS.map((_, m) => <th key={m}>M{m}</th>)}</tr></thead><tbody>{COHORTS.map((c, ci) => <tr key={c} className={hot === ci ? 'is-hot' : ''} onMouseEnter={() => setHot(ci)} onMouseLeave={() => setHot(null)}><th>{c}/26</th>{COHORTS.map((_, m) => { const v = retention(seg, ci, m); return <td key={m} style={{ ['--heat' as string]: v === null ? 0 : v / 100 }}>{v === null ? '—' : `${v}%`}</td>; })}</tr>)}</tbody></table></div></Widget>
        <Widget title="Curvas de retenção" subtitle="Cada coorte ao longo dos meses" className="demo-wide"><LineChart ariaLabel="Curvas de retenção por coorte" height={220} yDomain={[0, 100]} xTicks={[0, 1, 2, 3, 4, 5]} xLabel={(x) => `M${x}`} yFormat={(y) => `${nf(y, 0)}%`} series={curves.map((c) => ({ pts: c.pts, color: palette[c.ci]!, width: hot === c.ci ? 3.2 : 1.8 }))} tooltip={(x) => <><b>M{x}</b>{curves.filter((c) => c.pts[x]).map((c) => <span key={c.c}>{c.c}: {c.pts[x]!.y}%</span>)}</>} />{legend(curves.map((c) => ({ color: palette[c.ci]!, label: c.c })))}</Widget></>
        : <Widget title="Caminhos mais frequentes" subtitle="Primeiras sessões após criar a conta" className="demo-wide"><div className="demo-paths">{PATHS.map(({ steps, share }) => <div key={steps.join('-')}><span className="demo-path-share" style={{ ['--share' as string]: `${share * 2.2}%` }}>{share}%</span>{steps.map((s, i) => <span className={`demo-path-node${s === 'Abandonou' ? ' is-drop' : ''}`} key={i}>{s}</span>)}</div>)}</div></Widget>}
    </div>
  </>;
}

export function DemoReportView({ id }: { id: string }) {
  const valid = (['demo_anomaly', 'demo_sla', 'demo_customer'] as string[]).includes(id) ? id as DemoId : 'demo_anomaly', meta = META[valid];
  const [refresh, setRefresh] = useState(0), [stamp, setStamp] = useState(() => new Date()), [rows, setRows] = useState<(string | number)[][] | null>(null);
  return <main className="demo-report pg" style={{ ['--demo-accent' as string]: meta.accent }} data-report={valid}>
    <div className="demo-back"><Link to="/reports"><Icon name="arrowLeft" size={12} /> Relatórios</Link><span>/</span><span>Operações de Rede</span></div>
    <header className="demo-report-head"><span className="demo-badge-icon"><Icon name={meta.icon} size={20} /></span><div><div className="demo-eyebrow"><Badge tone="success" icon="check">Publicado · v1.0</Badge><Badge tone="neutral">{meta.kicker}</Badge><Badge tone="neutral" icon="info">Dados simulados</Badge></div><h1 className="pg-title">{meta.title}</h1><p className="pg-sub">{meta.sub}</p></div>
      <Button icon="download" isDisabled={!rows} onPress={() => rows && exportCsv(`${valid}.csv`, rows)}>Exportar CSV</Button><Button icon="refresh" variant="primary" onPress={() => { setRefresh((r) => r + 1); setStamp(new Date()); }}>Atualizar dados</Button></header>
    <div className="demo-report-meta"><span><Icon name="clock" size={12} /> Atualizado às {stamp.toLocaleTimeString('pt-BR')}</span><span><Icon name="data" size={12} /> Fonte: dados gerados no navegador</span><span className="flex-1" /><span>Período: 01 set – 07 out 2026</span></div>
    {valid === 'demo_anomaly' ? <AnomalyReport refresh={refresh} stamp={setRows} /> : valid === 'demo_sla' ? <SlaReport refresh={refresh} stamp={setRows} /> : <CustomerReport refresh={refresh} stamp={setRows} />}
    <footer className="demo-report-foot"><Icon name="info" size={12} /><span>Este relatório funciona inteiramente no navegador com dados sintéticos determinísticos. Filtros, limiares e simulações alteram o estado local; nenhuma conexão com backend é feita.</span></footer>
  </main>;
}
