/** Ecossistema de conectores do LDE (transporte × formato × extrator). Disponibilidade honesta: AVAILABLE / PREPARED / PLANNED. */
export type Avail = 'available' | 'prepared' | 'planned';
export type Cat = 'db' | 'wh' | 'files' | 'storage' | 'api' | 'apps' | 'realtime' | 'legacy' | 'docs' | 'geo' | 'custom';
export type FormKind = 'db' | 'odbc' | 'file' | 'rest' | 'webhook' | 'mqtt' | 'kafka' | 'sftp' | 'storage' | 'pdf' | 'saas' | 'geo' | 'custom';
export interface Connector { id: string; name: string; cat: Cat; desc: string; avail: Avail; form: FormKind; caps: string[]; port?: string }

export const CATS: { id: Cat | 'all' | 'recent' | 'fav'; label: string }[] = [
  { id: 'all', label: 'Todos' }, { id: 'recent', label: 'Recentes' }, { id: 'fav', label: 'Favoritos' }, { id: 'db', label: 'Bancos de dados' }, { id: 'wh', label: 'Data warehouses' }, { id: 'files', label: 'Arquivos' }, { id: 'storage', label: 'Armazenamento e transporte' },
  { id: 'api', label: 'APIs' }, { id: 'apps', label: 'Aplicações de negócio' }, { id: 'realtime', label: 'Tempo real' }, { id: 'legacy', label: 'Legado' }, { id: 'docs', label: 'Documentos' }, { id: 'geo', label: 'Geoespacial' }, { id: 'custom', label: 'Personalizado' },
];
export const AVAIL_LABEL: Record<Avail, string> = { available: 'Disponível', prepared: 'Preparado', planned: 'Planejado' };

const CAPS: Record<FormKind, string[]> = {
  db: ['Descoberta', 'Amostragem', 'Carga completa', 'Incremental', 'Leitura'], odbc: ['Descoberta', 'Amostragem', 'Carga completa', 'Leitura'], file: ['Descoberta', 'Amostragem', 'Carga completa', 'Leitura'],
  rest: ['Descoberta', 'Paginação', 'Incremental', 'Leitura'], webhook: ['Push', 'Deduplicação', 'Assinatura HMAC'], mqtt: ['Stream', 'QoS', 'Tempo real'], kafka: ['Stream', 'Offsets', 'Tempo real'], sftp: ['Descoberta', 'Padrões de arquivo', 'Agendamento'],
  storage: ['Descoberta', 'Amostragem', 'Incremental', 'Leitura'], pdf: ['OCR', 'Extração', 'Revisão humana'], saas: ['Descoberta', 'Incremental', 'OAuth', 'Leitura'], geo: ['Descoberta', 'Geometria', 'Detecção de CRS'], custom: ['SDK', 'Transporte × formato × extrator'],
};
const C = (id: string, name: string, cat: Cat, desc: string, avail: Avail, form: FormKind, extra: string[] = []): Connector => ({ id, name, cat, desc, avail, form, caps: [...(CAPS[form] ?? []), ...extra] });
const AV = 'available' as const, PR = 'prepared' as const, PL = 'planned' as const;

export const CONNECTORS: Connector[] = [
  C('postgres', 'PostgreSQL', 'db', 'Banco relacional', AV, 'db', ['Profiling pushdown']), C('mssql', 'Microsoft SQL Server', 'db', 'Banco relacional', AV, 'db', ['CDC']), C('mysql', 'MySQL', 'db', 'Banco relacional', AV, 'db'), C('mariadb', 'MariaDB', 'db', 'Banco relacional', PR, 'db'),
  C('oracle', 'Oracle Database', 'db', 'Banco relacional corporativo', PR, 'db', ['CDC']), C('db2', 'IBM Db2', 'db', 'Banco relacional corporativo', PR, 'db'), C('sqlite', 'SQLite', 'db', 'Banco embutido em arquivo', AV, 'db'), C('cockroach', 'CockroachDB', 'db', 'SQL distribuído', PL, 'db'),
  C('yugabyte', 'YugabyteDB', 'db', 'SQL distribuído', PL, 'db'), C('hana', 'SAP HANA', 'db', 'Banco em memória', PL, 'db'), C('teradata', 'Teradata', 'db', 'Banco analítico', PL, 'db'), C('firebird', 'Firebird', 'db', 'Banco relacional', PL, 'db'),
  C('informix', 'Informix', 'db', 'Banco relacional', PL, 'db'), C('access', 'Microsoft Access', 'db', 'Banco em arquivo (.mdb/.accdb)', PR, 'file'), C('odbc', 'Generic ODBC', 'db', 'Qualquer driver ODBC', AV, 'odbc'),
  C('clickhouse', 'ClickHouse', 'wh', 'Banco colunar analítico', PR, 'db', ['Profiling pushdown']), C('snowflake', 'Snowflake', 'wh', 'Data warehouse em nuvem', PR, 'db', ['Profiling pushdown']), C('bigquery', 'Google BigQuery', 'wh', 'Data warehouse em nuvem', PR, 'db', ['Profiling pushdown']),
  C('redshift', 'Amazon Redshift', 'wh', 'Data warehouse em nuvem', PR, 'db'), C('synapse', 'Azure Synapse', 'wh', 'Data warehouse em nuvem', PL, 'db'), C('databricks', 'Databricks SQL', 'wh', 'Lakehouse SQL', PL, 'db'), C('trino', 'Trino', 'wh', 'Motor SQL federado', PL, 'db'),
  C('presto', 'Presto', 'wh', 'Motor SQL federado', PL, 'db'), C('druid', 'Apache Druid', 'wh', 'OLAP em tempo real', PL, 'db'), C('starrocks', 'StarRocks', 'wh', 'OLAP MPP', PL, 'db'), C('duckdb', 'DuckDB', 'wh', 'OLAP embutido', AV, 'db'),
  C('csv', 'CSV', 'files', 'Texto delimitado', AV, 'file'), C('tsv', 'TSV', 'files', 'Texto delimitado por tabulação', AV, 'file'), C('txt', 'TXT', 'files', 'Texto simples', AV, 'file'), C('xlsx', 'Excel XLSX', 'files', 'Planilha com detecção de regiões', AV, 'file', ['Detecção de tabelas']),
  C('xls', 'Excel XLS', 'files', 'Planilha legada', AV, 'file', ['Detecção de tabelas']), C('ods', 'ODS', 'files', 'Planilha OpenDocument', PR, 'file'), C('json', 'JSON', 'files', 'Documento JSON com estruturas aninhadas', AV, 'file', ['Estrutura aninhada']), C('ndjson', 'NDJSON', 'files', 'JSON por linha', AV, 'file'),
  C('xml', 'XML', 'files', 'Documentos XML (ex.: NF-e)', AV, 'file', ['Estrutura aninhada']), C('parquet', 'Parquet', 'files', 'Formato colunar', AV, 'file'), C('avro', 'Avro', 'files', 'Formato binário com schema', PR, 'file'), C('orc', 'ORC', 'files', 'Formato colunar', PL, 'file'),
  C('dbf', 'DBF', 'files', 'dBase / FoxPro / Clipper', PR, 'file'), C('fixed', 'Fixed Width', 'files', 'Largura fixa com layout', AV, 'file'),
  C('upload', 'Upload', 'storage', 'Envio direto pelo navegador', AV, 'file'), C('localfolder', 'Local Folder', 'storage', 'Pasta no servidor', AV, 'sftp'), C('watched', 'Watched Folder', 'storage', 'Pasta monitorada por novos arquivos', AV, 'sftp'), C('url', 'URL', 'storage', 'Arquivo em URL pública', AV, 'file'),
  C('http', 'HTTP/HTTPS', 'storage', 'Download com autenticação', AV, 'file'), C('ftp', 'FTP', 'storage', 'Transferência de arquivos', PR, 'sftp'), C('sftp', 'SFTP', 'storage', 'Transferência segura de arquivos', AV, 'sftp'), C('smb', 'Network Share', 'storage', 'Compartilhamento SMB/CIFS', PR, 'sftp'),
  C('s3', 'Amazon S3', 'storage', 'Armazenamento de objetos', AV, 'storage'), C('s3c', 'S3 Compatible', 'storage', 'Armazenamento compatível com S3', PR, 'storage'), C('r2', 'Cloudflare R2', 'storage', 'Armazenamento de objetos', PR, 'storage'), C('minio', 'MinIO', 'storage', 'Armazenamento de objetos', PR, 'storage'),
  C('azblob', 'Azure Blob Storage', 'storage', 'Armazenamento de objetos', PR, 'storage'), C('gcs', 'Google Cloud Storage', 'storage', 'Armazenamento de objetos', PR, 'storage'),
  C('rest', 'REST API', 'api', 'API HTTP com paginação e cursores', AV, 'rest'), C('openapi', 'OpenAPI', 'api', 'REST a partir de uma especificação', PR, 'rest', ['Importa spec']), C('graphql', 'GraphQL', 'api', 'Consultas GraphQL', PR, 'rest'), C('soap', 'SOAP', 'api', 'Serviços WSDL', PL, 'rest'), C('http-generic', 'Generic HTTP', 'api', 'Requisições HTTP personalizadas', AV, 'rest'),
  C('salesforce', 'Salesforce', 'apps', 'CRM', PR, 'saas'), C('hubspot', 'HubSpot', 'apps', 'CRM e marketing', PR, 'saas'), C('dynamics', 'Microsoft Dynamics 365', 'apps', 'CRM / ERP', PL, 'saas'), C('pipedrive', 'Pipedrive', 'apps', 'CRM', PL, 'saas'),
  C('sap', 'SAP', 'apps', 'ERP', PL, 'saas'), C('oracle-erp', 'Oracle ERP', 'apps', 'ERP', PL, 'saas'), C('totvs', 'TOTVS', 'apps', 'ERP brasileiro', PR, 'saas'), C('sankhya', 'Sankhya', 'apps', 'ERP brasileiro', PR, 'saas'),
  C('senior', 'Senior', 'apps', 'ERP brasileiro', PL, 'saas'), C('omie', 'Omie', 'apps', 'ERP em nuvem', PR, 'saas'), C('bling', 'Bling', 'apps', 'ERP em nuvem', PR, 'saas'),
  C('gsheets', 'Google Sheets', 'apps', 'Planilhas online', AV, 'saas'), C('sharepoint', 'SharePoint', 'apps', 'Documentos e listas', PR, 'saas'), C('onedrive', 'OneDrive', 'apps', 'Arquivos em nuvem', PR, 'saas'), C('gdrive', 'Google Drive', 'apps', 'Arquivos em nuvem', PR, 'saas'), C('excel-online', 'Excel Online', 'apps', 'Planilhas online', PR, 'saas'),
  C('ga', 'Google Analytics', 'apps', 'Analytics web', AV, 'saas'), C('gads', 'Google Ads', 'apps', 'Publicidade', PR, 'saas'), C('meta', 'Meta Ads', 'apps', 'Publicidade', PR, 'saas'), C('shopify', 'Shopify', 'apps', 'E-commerce', AV, 'saas'), C('woo', 'WooCommerce', 'apps', 'E-commerce', PR, 'saas'),
  C('stripe', 'Stripe', 'apps', 'Pagamentos', PR, 'saas'), C('mercadopago', 'Mercado Pago', 'apps', 'Pagamentos', PR, 'saas'), C('pagseguro', 'PagSeguro', 'apps', 'Pagamentos', PL, 'saas'),
  C('webhook', 'Webhook', 'realtime', 'Eventos recebidos por HTTP', AV, 'webhook'), C('kafka', 'Kafka', 'realtime', 'Stream de eventos', AV, 'kafka'), C('redpanda', 'Redpanda', 'realtime', 'Stream compatível com Kafka', PR, 'kafka'), C('mqtt', 'MQTT', 'realtime', 'Mensageria IoT', AV, 'mqtt'),
  C('debezium', 'Debezium CDC', 'realtime', 'Captura de mudanças de banco', PR, 'kafka', ['CDC']), C('stream', 'Generic Event Stream', 'realtime', 'Fluxo de eventos genérico', PR, 'webhook'),
  C('as400', 'IBM AS/400 / IBM i', 'legacy', 'Sistemas IBM i via ODBC', AV, 'odbc', ['EBCDIC']), C('progress', 'Progress', 'legacy', 'Banco legado', PL, 'odbc'), C('foxpro', 'FoxPro', 'legacy', 'Tabelas DBF legadas', PR, 'file'), C('clipper', 'Clipper / DBF', 'legacy', 'Tabelas DBF legadas', PR, 'file'),
  C('cp850', 'CP850 files', 'legacy', 'Arquivos em codificação DOS', AV, 'file', ['Decodificação CP850']), C('ebcdic', 'EBCDIC', 'legacy', 'Arquivos mainframe', PR, 'file', ['Copybook COBOL']), C('sftp-exports', 'SFTP exports', 'legacy', 'Exportações periódicas via SFTP', AV, 'sftp'), C('watched-exports', 'Watched folder exports', 'legacy', 'Exportações em pasta monitorada', AV, 'sftp'),
  C('pdf', 'PDF', 'docs', 'Extração de campos com OCR', AV, 'pdf'), C('scanpdf', 'Scanned PDF', 'docs', 'PDF digitalizado', PR, 'pdf'), C('jpg', 'JPG', 'docs', 'Imagem de documento', PR, 'pdf'), C('png', 'PNG', 'docs', 'Imagem de documento', PR, 'pdf'), C('tiff', 'TIFF', 'docs', 'Imagem de documento', PR, 'pdf'),
  C('docx', 'DOCX', 'docs', 'Documento Word', PL, 'pdf'), C('invoice-batch', 'Invoice batch', 'docs', 'Lote de notas fiscais', AV, 'pdf'), C('doc-batch', 'Generic document batch', 'docs', 'Lote de documentos genérico', PR, 'pdf'),
  C('geojson', 'GeoJSON', 'geo', 'Feições geoespaciais', AV, 'geo'), C('kml', 'KML', 'geo', 'Google Earth', PR, 'geo'), C('kmz', 'KMZ', 'geo', 'KML compactado', PR, 'geo'), C('shp', 'Shapefile', 'geo', 'Formato vetorial Esri', PR, 'geo'),
  C('gpkg', 'GeoPackage', 'geo', 'Formato vetorial OGC', PR, 'geo'), C('geoparquet', 'GeoParquet', 'geo', 'Parquet geoespacial', PL, 'geo'), C('postgis', 'PostGIS', 'geo', 'PostgreSQL geoespacial', PR, 'db'), C('wfs', 'WFS', 'geo', 'Web Feature Service', PL, 'geo'), C('wms', 'WMS', 'geo', 'Web Map Service', PL, 'geo'),
  C('custom-source', 'Custom Source Connector', 'custom', 'Conector próprio via SDK', PR, 'custom'), C('custom-transport', 'Custom Transport', 'custom', 'Novo meio de transporte', PR, 'custom'), C('custom-decoder', 'Custom Decoder', 'custom', 'Novo formato / decodificador', PR, 'custom'), C('custom-extractor', 'Custom Extractor', 'custom', 'Novo extrator semântico', PR, 'custom'),
];
export const connectorById = (id: string) => CONNECTORS.find((c) => c.id === id);

/* ───────── formulários por tipo de conector ───────── */
export interface FField { k: string; label: string; kind: 'text' | 'password' | 'select' | 'number' | 'switch' | 'file'; def?: string | number | boolean; opts?: string[]; hint?: string; w?: 'half' | 'full' }
export const FORMS: Record<FormKind, { title: string; auth: string; fields: FField[]; adv: FField[] }> = {
  db: { title: 'Banco de dados', auth: 'Usuário / senha', fields: [
    { k: 'host', label: 'Host', kind: 'text', def: 'db.novalink.internal' }, { k: 'port', label: 'Porta', kind: 'number', def: 5432, w: 'half' }, { k: 'database', label: 'Banco', kind: 'text', def: 'operations', w: 'half' }, { k: 'schema', label: 'Schema', kind: 'text', def: 'public', w: 'half' },
    { k: 'user', label: 'Usuário', kind: 'text', def: 'biweb_reader', w: 'half' }, { k: 'password', label: 'Senha', kind: 'password', def: 'secret-value', w: 'half' }, { k: 'ssl', label: 'SSL', kind: 'select', opts: ['Exigir', 'Preferir', 'Desativado'], def: 'Exigir', w: 'half' },
  ], adv: [{ k: 'ssh', label: 'Túnel SSH', kind: 'switch', def: false }, { k: 'timeout', label: 'Timeout (s)', kind: 'number', def: 30 }, { k: 'ro', label: 'Validar somente leitura', kind: 'switch', def: true }] },
  odbc: { title: 'ODBC', auth: 'Usuário / senha', fields: [{ k: 'dsn', label: 'DSN ou string de conexão', kind: 'text', def: 'DSN=AS400_PROD;SYSTEM=ibmi.novalink.internal' }, { k: 'user', label: 'Usuário', kind: 'text', def: 'BIWEB', w: 'half' }, { k: 'password', label: 'Senha', kind: 'password', def: 'secret-value', w: 'half' }, { k: 'enc', label: 'Codificação', kind: 'select', opts: ['UTF-8', 'CP850', 'CP1252', 'EBCDIC (CP037)'], def: 'CP850', w: 'half' }, { k: 'lib', label: 'Biblioteca / schema', kind: 'text', def: 'LIB_ERP', w: 'half' }], adv: [{ k: 'timeout', label: 'Timeout (s)', kind: 'number', def: 60 }, { k: 'ro', label: 'Validar somente leitura', kind: 'switch', def: true }] },
  file: { title: 'Arquivo', auth: 'Nenhuma', fields: [
    { k: 'file', label: 'Arquivo ou local', kind: 'file', def: 'vendas_2026.csv' }, { k: 'enc', label: 'Codificação', kind: 'select', opts: ['UTF-8', 'ISO-8859-1', 'CP1252', 'CP850'], def: 'UTF-8', w: 'half' }, { k: 'delim', label: 'Delimitador', kind: 'select', opts: ['Ponto e vírgula (;)', 'Vírgula (,)', 'Tabulação', 'Barra vertical (|)'], def: 'Ponto e vírgula (;)', w: 'half' },
    { k: 'dec', label: 'Separador decimal', kind: 'select', opts: ['Vírgula (,)', 'Ponto (.)'], def: 'Vírgula (,)', w: 'half' }, { k: 'header', label: 'Linha de cabeçalho', kind: 'number', def: 1, w: 'half' }, { k: 'datefmt', label: 'Formato de data', kind: 'select', opts: ['dd/mm/aaaa', 'aaaa-mm-dd', 'mm/dd/aaaa', 'Detectar'], def: 'Detectar', w: 'half' },
  ], adv: [{ k: 'skip', label: 'Ignorar linhas de total', kind: 'switch', def: true }, { k: 'regions', label: 'Detectar várias tabelas por aba', kind: 'switch', def: true }] },
  rest: { title: 'API REST', auth: 'Bearer / API key / OAuth', fields: [
    { k: 'url', label: 'URL base', kind: 'text', def: 'https://api.crm.exemplo.com/v2' }, { k: 'auth', label: 'Autenticação', kind: 'select', opts: ['Bearer token', 'API key', 'OAuth 2.0', 'Basic'], def: 'Bearer token', w: 'half' }, { k: 'token', label: 'Token', kind: 'password', def: 'secret-value', w: 'half' },
    { k: 'headers', label: 'Cabeçalhos', kind: 'text', def: 'Accept: application/json', hint: 'Um por linha' }, { k: 'resources', label: 'Recursos', kind: 'text', def: '/customers, /deals, /activities' }, { k: 'pagination', label: 'Paginação', kind: 'select', opts: ['Cursor', 'Offset / limit', 'Página', 'Link header'], def: 'Cursor', w: 'half' }, { k: 'cursor', label: 'Campo incremental', kind: 'text', def: 'updated_at', w: 'half' }, { k: 'rate', label: 'Limite (req/min)', kind: 'number', def: 500, w: 'half' },
  ], adv: [{ k: 'retry', label: 'Tentar novamente em 429/5xx', kind: 'switch', def: true }, { k: 'timeout', label: 'Timeout (s)', kind: 'number', def: 30 }] },
  webhook: { title: 'Webhook', auth: 'Assinatura HMAC', fields: [{ k: 'endpoint', label: 'Endpoint (gerado)', kind: 'text', def: 'https://ingest.biweb.io/v1/ingest/ws_novalink/payments' }, { k: 'secret', label: 'Segredo', kind: 'password', def: 'whsec-value' }, { k: 'sig', label: 'Método de assinatura', kind: 'select', opts: ['HMAC-SHA256', 'HMAC-SHA1', 'Nenhum (não recomendado)'], def: 'HMAC-SHA256', w: 'half' }, { k: 'eid', label: 'Campo ID do evento', kind: 'text', def: 'event_id', w: 'half' }], adv: [{ k: 'dedup', label: 'Ignorar duplicados (janela 24 h)', kind: 'switch', def: true }, { k: 'retention', label: 'Retenção RAW (dias)', kind: 'number', def: 30 }] },
  mqtt: { title: 'MQTT', auth: 'Usuário / senha ou certificado', fields: [{ k: 'broker', label: 'Broker', kind: 'text', def: 'mqtts://broker.novalink.internal:8883' }, { k: 'topic', label: 'Tópico', kind: 'text', def: 'telemetry/#', w: 'half' }, { k: 'qos', label: 'QoS', kind: 'select', opts: ['0 · no máximo uma vez', '1 · ao menos uma vez', '2 · exatamente uma vez'], def: '1 · ao menos uma vez', w: 'half' }, { k: 'user', label: 'Usuário', kind: 'text', def: 'biweb', w: 'half' }, { k: 'password', label: 'Senha', kind: 'password', def: 'secret-value', w: 'half' }], adv: [{ k: 'clean', label: 'Sessão limpa', kind: 'switch', def: false }, { k: 'batch', label: 'Janela de lote (ms)', kind: 'number', def: 500 }] },
  kafka: { title: 'Kafka', auth: 'SASL / TLS', fields: [{ k: 'brokers', label: 'Brokers', kind: 'text', def: 'kafka-1:9093,kafka-2:9093' }, { k: 'topic', label: 'Tópico', kind: 'text', def: 'billing.events', w: 'half' }, { k: 'group', label: 'Consumer group', kind: 'text', def: 'biweb-lde', w: 'half' }, { k: 'sasl', label: 'SASL', kind: 'select', opts: ['PLAIN', 'SCRAM-SHA-512', 'OAUTHBEARER'], def: 'SCRAM-SHA-512', w: 'half' }, { k: 'password', label: 'Segredo', kind: 'password', def: 'secret-value', w: 'half' }], adv: [{ k: 'offset', label: 'Offset inicial', kind: 'select', opts: ['latest', 'earliest'], def: 'latest' }] },
  sftp: { title: 'SFTP / pasta', auth: 'Chave SSH ou senha', fields: [{ k: 'host', label: 'Host', kind: 'text', def: 'sftp.parceiro.com.br' }, { k: 'port', label: 'Porta', kind: 'number', def: 22, w: 'half' }, { k: 'user', label: 'Usuário', kind: 'text', def: 'biweb', w: 'half' }, { k: 'path', label: 'Caminho', kind: 'text', def: '/exports/vendas', w: 'half' }, { k: 'pattern', label: 'Padrão de arquivo', kind: 'text', def: 'sales_*.csv', w: 'half' }, { k: 'schedule', label: 'Agenda', kind: 'select', opts: ['Diário · 05:30', 'A cada hora', 'A cada 15 min', 'Manual'], def: 'Diário · 05:30' }], adv: [{ k: 'archive', label: 'Mover arquivos processados', kind: 'switch', def: true }] },
  storage: { title: 'Armazenamento de objetos', auth: 'Chave de acesso / IAM', fields: [{ k: 'bucket', label: 'Bucket', kind: 'text', def: 'novalink-datalake' }, { k: 'prefix', label: 'Prefixo', kind: 'text', def: 'events/2026/', w: 'half' }, { k: 'region', label: 'Região', kind: 'text', def: 'sa-east-1', w: 'half' }, { k: 'key', label: 'Chave de acesso', kind: 'text', def: 'AKIA••••••••', w: 'half' }, { k: 'secret', label: 'Segredo', kind: 'password', def: 'secret-value', w: 'half' }, { k: 'fmt', label: 'Formato', kind: 'select', opts: ['Parquet', 'CSV', 'JSON', 'Avro'], def: 'Parquet' }], adv: [{ k: 'partition', label: 'Detectar partições', kind: 'switch', def: true }] },
  pdf: { title: 'Documentos', auth: 'Nenhuma', fields: [{ k: 'src', label: 'Upload ou pasta', kind: 'file', def: 'notas_outubro/' }, { k: 'dtype', label: 'Tipo de documento', kind: 'select', opts: ['Nota fiscal de serviço', 'Boleto', 'Contrato', 'Genérico'], def: 'Nota fiscal de serviço', w: 'half' }, { k: 'schema', label: 'Schema de extração', kind: 'select', opts: ['Fornecedor, CNPJ, emissão, total', 'Personalizado'], def: 'Fornecedor, CNPJ, emissão, total', w: 'half' }, { k: 'ocr', label: 'OCR', kind: 'select', opts: ['Automático', 'Sempre', 'Desligado'], def: 'Automático', w: 'half' }, { k: 'ai', label: 'Política de extração com IA', kind: 'select', opts: ['Desligada', 'Somente metadados', 'Valores mascarados', 'Permitida'], def: 'Somente metadados', w: 'half' }], adv: [{ k: 'conf', label: 'Revisão humana abaixo de (%)', kind: 'number', def: 80 }] },
  saas: { title: 'Aplicação de negócio', auth: 'OAuth 2.0', fields: [{ k: 'account', label: 'Conta / domínio', kind: 'text', def: 'novalink.exemplo.com' }, { k: 'auth', label: 'Autenticação', kind: 'select', opts: ['OAuth 2.0', 'API key'], def: 'OAuth 2.0', w: 'half' }, { k: 'scope', label: 'Escopos (somente leitura)', kind: 'text', def: 'read', w: 'half' }, { k: 'objects', label: 'Objetos', kind: 'text', def: 'Todos os objetos padrão' }], adv: [{ k: 'rate', label: 'Respeitar limites da API', kind: 'switch', def: true }] },
  geo: { title: 'Geoespacial', auth: 'Nenhuma', fields: [{ k: 'file', label: 'Arquivo ou serviço', kind: 'file', def: 'field_assets.geojson' }, { k: 'crs', label: 'CRS', kind: 'select', opts: ['Detectar', 'EPSG:4326', 'EPSG:31983 (SIRGAS 2000)'], def: 'Detectar', w: 'half' }, { k: 'geom', label: 'Geometria', kind: 'select', opts: ['Detectar', 'Point', 'Line', 'Polygon'], def: 'Detectar', w: 'half' }], adv: [{ k: 'simplify', label: 'Simplificar geometrias na prévia', kind: 'switch', def: true }] },
  custom: { title: 'Conector personalizado', auth: 'Definida pelo SDK', fields: [{ k: 'transport', label: 'Transporte', kind: 'select', opts: ['HTTP', 'SFTP', 'S3', 'Socket', 'Arquivo local'], def: 'SFTP', w: 'half' }, { k: 'format', label: 'Formato', kind: 'select', opts: ['CSV', 'JSON', 'XML', 'Parquet', 'Binário proprietário'], def: 'Binário proprietário', w: 'half' }, { k: 'extractor', label: 'Extrator', kind: 'select', opts: ['Tabela', 'Documento', 'Eventos', 'Personalizado'], def: 'Personalizado' }, { k: 'pkg', label: 'Pacote do conector', kind: 'text', def: '@novalink/connector-custom' }], adv: [] },
};

/* ───────── descoberta simulada ───────── */
export interface DNode { id: string; label: string; count?: string; children?: DNode[] }
const T = (id: string, label: string, count?: string): DNode => ({ id, label, count });
export function discover(form: FormKind): { facts: [string, string][]; tree: DNode[] } {
  switch (form) {
    case 'db': case 'odbc': return { facts: [['4', 'schemas'], ['32', 'tabelas'], ['8', 'views'], ['428', 'colunas']], tree: [
      { id: 'public', label: 'public', count: '18', children: [T('public.customers', 'customers', '412 mil'), T('public.orders', 'orders', '1,8 mi'), T('public.order_items', 'order_items', '5,1 mi'), T('public.products', 'products', '9,4 mil')] },
      { id: 'billing', label: 'billing', count: '9', children: [T('billing.invoices', 'invoices', '2,2 mi'), T('billing.payments', 'payments', '1,9 mi'), T('billing.plans', 'plans', '42')] }, { id: 'audit', label: 'audit', count: '5', children: [T('audit.log', 'log', '48 mi'), T('audit.sessions', 'sessions', '1,1 mi')] } ] };
    case 'file': return { facts: [['1', 'arquivo'], ['3', 'abas / tabelas'], ['38', 'colunas'], ['12', 'linhas de totais ignoradas']], tree: [{ id: 'f', label: 'vendas_2026.csv', count: '412 mil linhas', children: [T('f.sales', 'Tabela principal', '412 mil'), T('f.totals', 'Linha de totais (ignorada)', '12')] }] };
    case 'rest': case 'saas': return { facts: [['3', 'recursos'], ['184', 'campos'], ['1', 'cursor incremental'], ['500', 'req/min']], tree: [T('r.customers', 'customers', '398 mil'), T('r.deals', 'deals', '61 mil'), T('r.activities', 'activities', '884 mil')] };
    case 'webhook': return { facts: [['1', 'endpoint'], ['3', 'tipos de evento'], ['9', 'campos'], ['HMAC', 'assinatura']], tree: [T('w.paid', 'payment.paid'), T('w.failed', 'payment.failed'), T('w.refund', 'refund')] };
    case 'mqtt': case 'kafka': return { facts: [['4', 'tópicos'], ['7', 'campos no payload'], ['12,4 mil', 'eventos/s'], ['JSON', 'formato']], tree: [T('t.events', 'telemetry/events', '12,4 mil/s'), T('t.alarms', 'telemetry/alarms', '34/s'), T('t.status', 'telemetry/status', '210/s'), T('t.cfg', 'telemetry/config', '2/s')] };
    case 'sftp': return { facts: [['27', 'arquivos que casam com o padrão'], ['1', 'layout'], ['412 mil', 'linhas no último'], ['CSV', 'formato']], tree: [T('s.1', 'sales_20261010.csv', '412 mil'), T('s.2', 'sales_20261009.csv', '398 mil'), T('s.3', 'sales_20261008.csv', '405 mil')] };
    case 'storage': return { facts: [['14', 'prefixos'], ['3.100', 'objetos'], ['38 GB', 'volume'], ['Parquet', 'formato']], tree: [T('o.events', 'events/2026/', '38 GB'), T('o.clicks', 'clicks/2026/', '9 GB')] };
    case 'pdf': return { facts: [['320', 'arquivos'], ['1', 'layout reconhecido'], ['6', 'campos extraíveis'], ['29', 'prontos para revisão']], tree: [T('d.inv', 'Notas fiscais de serviço', '320')] };
    case 'geo': return { facts: [['1', 'camada'], ['82.419', 'feições'], ['Point', 'geometria'], ['EPSG:4326', 'CRS']], tree: [T('g.assets', 'assets', '82.419')] };
    default: return { facts: [['1', 'recurso'], ['—', ''], ['—', ''], ['—', '']], tree: [T('c.1', 'Recurso do conector')] };
  }
}
